### ISSUE TITLE
MAINT: Link to Github from Network Book Site

### ISSUE THREAD

**Issue by HumphreyYang** [QuantEcon/book-dp1#11]
Hi @jstac,

The hyperlink in the site for the [network book](https://networks.quantecon.org/) for GitHub has led me to this repo, which I think is incorrect. 

The screenshot shows the GitHub icon that is associated with the misleading hyperlink:

<img width="733" alt="image" src="https://user-images.githubusercontent.com/39026988/233838005-d6af2853-6941-4f9d-8d27-4c6ea3a08359.png">

**Comment by HumphreyYang** [comment]
This issue has been addressed in [book-networks#49](https://github.com/QuantEcon/book-networks/pull/49).

**Comment by jstac** [comment]
Good catch @HumphreyYang !
