### ISSUE TITLE
Errata

### ISSUE THREAD

**Issue by pitmonticone** [QuantEcon/book-dp1#12]
I've opened this issue to collect errata of all sorts while consulting the textbook.

Hi @jstac and @thomassargent30, is it possible to make the source .tex file public so we can increase the efficiency of the correction procedure?

**Comment by jstac** [comment]
Thanks @pitmonticone !  Fixed.

I wish we could share the source but it's now accepted for publication with Cambridge UP and our contract won't let us do that.  (Fortunately we can leave a free PDF on the internet.)

Please keep them coming!

**Comment by jstac** [comment]
(@pitmonticone , since you have contributed to QuantEcon I would be happy to give you access to the private repo that contains the source code, as long as you don't share it.)

**Comment by pitmonticone** [comment]
> (@pitmonticone , since you have contributed to QuantEcon I would be happy to give you access to the private repo that contains the source code, as long as you don't share it.)

Sure @jstac, glad to help with the proofreading and available to join the organization if you believe it's useful.

**Comment by jstac** [comment]
I've added you to the repo @pitmonticone and all help is greatly appreciated.  You might have write permission once you accept the invite but please only work through PRs.

**Comment by pitmonticone** [comment]
Ok, thanks @jstac.
